name: Deploy Django app to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
      - uses: akhileshns/heroku-deploy@v3.13.15
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "test-mkr"
          heroku_email: "yulia.andreyeva@knu.ua"
